# Generated by Django 2.2.6 on 2019-10-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191011_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allowed_toppings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='toppings',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
