# Generated by Django 2.2.6 on 2019-10-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED')], default='pending', max_length=50),
        ),
    ]
