# Generated by Django 2.2.6 on 2019-10-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='toppings',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
